version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: apishield-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: apishield-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: shield_admin
      RABBITMQ_DEFAULT_PASS: shield_secret
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    container_name: apishield-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: apishield
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
